# Site settings
title: Star Robbins & Company
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://starrobbins.com" # the base hostname & protocol for your site

excerpt_separator: ""

exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

collections:
  questions:
    output: true


# Prose config
# Prose settings
prose:
  media: 'assets'
  rooturl: "_posts"
  siteurl: "https://starrobbinsandcompany.github.io/"
  # relativeLinks: "https://www.healthcare.gov/resources/prose/relativeLinks.jsonp"
  # site:
  #   tags: "https://www.healthcare.gov/api/tags.jsonp"
  metadata:
    _posts/articles:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "meta-description"
        field:
          element: "text"
          label: "Meta Description"
          value: ""
      - name: "title-short"
        field:
          element: "text"
          label: "Title Short"
          value: ""
      - name: "bite"
        field:
          element: "text"
          label: "Bite"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: *languages
          selected: "en"
      - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "article"
              value: "basic"
            - name: "multi-part article"
              value: "basic-nav-left"
            - name: "article, no sidebar"
              value: "basic-full-page"
          selected: "basic"
